application: php-opt
version: 1
runtime: php55
api_version: 1

handlers:
- url: /
  script: form.html

- url: /index\.html
  script: form.html

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /.*
  script: form.html